port: 4000

name: Duckietown
markdown: redcarpet
pygments: true
baseurl: /inicio

links:
    -title: Home
     url:/

    -title: Proyecto
     url:/proyecto.html

    -title: Curso
     url:/proyecto/curso 

    -title: Material del Curso
     url:/material-del-curso