- name: 'Enzo Bassano'

- name: 'Luis Cárcamo'

- name: 'Andrés Cerda'

- name: 'Tomás De la Sotta'

- name: 'Santiago Ernst'

- name: 'Benjamín Hunfan'

- name: 'Miguel Jaramillo'

- name: 'Eduardo Jorquera'

- name: 'Eduardo Loayza'

- name: 'Pedro Martínez'

- name: 'Camilo Meneses'

- name: 'Raimundo Olckers'

- name: 'Dario Osses'

- name: 'Luis Plaza'

- name: 'Ignacio Poblete'

- name: 'Ariel Riveros'

- name: 'Emilio Roa'

- name: 'Diego Rubio'

- name: 'Maximiliano Varas'

- name: 'Sebastián Zapata'