- name: 'Amaru Ahumada'

- name: 'Gerald Barnert'

- name: 'Christian Briceño'

- name: 'Felipe Bustos'

- name: 'Valentina Castro'

- name: 'Nicolás Consuegra'

- name: 'Esperanza Díaz'

- name: 'Alonso Díaz'

- name: 'Jorge Gutiérrez'

- name: 'Esteban Lopez'

- name: 'Rentato Loyola'

- name: 'Álvaro Manríquez'

- name: 'Valentina Nuñez'

- name: 'Monserrat Prado'

- name: 'Camilo Rosas'

- name: 'Cristóbal Tapia'

- name: 'Cristóbal Torres'

- name: 'Rodrigo Vega'

- name: 'Tomás Villega'

- name: 'Daniel Zaro'
